version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: trello-clone-api
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped

  # app:
  #   container_name: trello_clone_api_container
  #   build: .
  #   environment:
  #     DATABASE_URL: "postgresql://postgres:password@postgres_container:5432/trello-clone-api?schema=public"
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  #   volumes:
  #     - .:/app
  #   command: npm run start:prod

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: