version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: fastify-prisma
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  # app:
  #   container_name: trello_clone_api_container
  #   build: .
  #   environment:
  #     DATABASE_URL: postgresql://postgres:password@postgres_container:5432/trello-clone-api?schema=public
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/app
  #   command: npm run start:prod

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prom/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  postgres:
  prom_data:
  grafana-storage: {}
