version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${KNEX_USERNAME}
      POSTGRES_PASSWORD: ${KNEX_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${KNEX_DATABASE}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  app:
    container_name: trello_clone_api_container
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BASE_WEB_URL: ${BASE_WEB_URL}
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - .:/app
    command: npm run start:prod

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
